#!/usr/bin/env bash
# 1-install_nginx_web_server

# Update package list and install nginx
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start