#!/usr/bin/env bash
# 1-install_nginx_web_server

# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start