#!/usr/bin/env bash
# Bash script to ping an IP address
# Check if an argument is provided
if [ $# -eq 0 ]; then
    script_name=$(basename "$0")
    echo "Usage: $script_name {IP_ADDRESS}"
    exit 1
else
	ip_address=$1
	ping -c 5 $ip_address
fi
