#!/usr/bin/env bash
# Bash script to ping an IP address
# Check if an argument is provided
if [ $# -eq 0 ]; then
    script_name=$(basename "$0")
    echo "Usage: $script_name {IP_ADDRESS}"
    exit 1
fi
# Extract the IP address from the command line argument
ip_address=$1
# Perform ping 5 times and display the results
ping -c 5 $ip_address
