#!/usr/bin/env bash
# Create the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid

# Trap signals and define corresponding actions
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -f /var/run/myscript.pid && exit" SIGQUIT SIGTERM

# Display To infinity and beyond indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done;
