#!/usr/bin/env bash
# manager for manage_my_process

RUN_SCRIPT="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

case "$1" in
	start)
		$RUN_SCRIPT &
		echo $! > "$PID_FILE"
		echo "manage_my_process started"
		;;
	stop)
		PID=$(cat "$PID_FILE")
		kill "$PID"
		rm "$PID_FILE"
		echo "manage_my_process stopped"
		;;
	restart)
		PID=$(cat "$PID_FILE")
		kill -s SIGSTOP "$PID"
		rm "$PID_FILE"
		$RUN_SCRIPT & > $PID_FILE
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac

exit 0
