#!/usr/bin/env bash
# manager for manage_my_process

MANAGE_SCRIPT="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

case "$1" in
    start)
	"$MANAGE_SCRIPT" &
        echo "$!" > "$PID_FILE"
        echo "manage_my_process started";;
    stop)
	kill "$(cat "$PID_FILE")"
        rm -f "$PID_FILE"
        echo "manage_my_process stopped";;
    restart)
    	rm -f "$PID_FILE"
    	"$MANAGE_SCRIPT" &
    	echo "$!" > "$PID_FILE"
    	echo "manage_my_process restarted";;
    *)
        echo "Usage: manage_my_process {start|stop|restart}";;
esac
