#!/usr/bin/env bash
# manager for manage_my_process

MANAGE_SCRIPT="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

start_process() {
    if [ -e "$PID_FILE" ]; then
        echo "Error: manage_my_process is already running (PID $(cat "$PID_FILE"))."
    else
        "$MANAGE_SCRIPT" &
        echo "$!" > "$PID_FILE"
        echo "manage_my_process started"
    fi
}

stop_process() {
    if [ -e "$PID_FILE" ]; then
        PID=$(cat "$PID_FILE")
        kill "$PID"
        rm -f "$PID_FILE"
        echo "manage_my_process stopped"
    else
        echo "Error: manage_my_process is not running."
    fi
}

restart_process() {
    kill "$(cat "$PID_FILE")"
    rm -f "$PID_FILE"
    "$MANAGE_SCRIPT" &
    echo "$!" > "$PID_FILE"
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start_process;;
    stop)
        stop_process;;
    restart)
        restart_process;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}";;
esac
