#!/usr/bin/env bash
# This script gives information about the school file

file="school"

# Check if the file exists
if [ -e "$file" ]; then
    echo "$file file exists"

    # Check if the file is empty
    if [ -s "$file" ]; then
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi

    # Check if the file is a regular file
    if [ -f "$file" ]; then
        echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
