#!/usr/bin/env bash
# This script configures an Ubuntu server to meet specific hostname resolution requirements.

sudo cp /etc/hosts /etc/hosts.bak
sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+ facebook.com/8.8.8.8 facebook.com/' /etc/hosts
cat /etc/hosts
